services:
  - type: web
    name: ixy_web_prod
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ixy_db_prod
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: ixy_db_prod
    plan: starter
